/* exported fontAwesome */

const fontAwesome = [
  ['fa-500px', '500px', '', '\uf26e'],
  ['fa-address-book-o', 'Address Book O', '', '\uf2ba'],
  ['fa-address-book', 'Address Book', '', '\uf2b9'],
  ['fa-address-card-o', 'Address Card O', '', '\uf2bc'],
  ['fa-address-card', 'Address Card', '', '\uf2bb'],
  ['fa-adjust', 'Adjust', '', '\uf042'],
  ['fa-adn', 'Adn', '', '\uf170'],
  ['fa-align-center', 'Align Center', '', '\uf037'],
  ['fa-align-justify', 'Align Justify', '', '\uf039'],
  ['fa-align-left', 'Align Left', '', '\uf036'],
  ['fa-align-right', 'Align Right', '', '\uf038'],
  ['fa-amazon', 'Amazon', '', '\uf270'],
  ['fa-ambulance', 'Ambulance', '', '\uf0f9'],
  [
    'fa-american-sign-language-interpreting',
    'American Sign Language Interpreting',
    '',
    '\uf2a3',
  ],
  ['fa-anchor', 'Anchor', '', '\uf13d'],
  ['fa-android', 'Android', '', '\uf17b'],
  ['fa-angellist', 'Angellist', '', '\uf209'],
  ['fa-angle-double-down', 'Angle Double Down', '', '\uf103'],
  ['fa-angle-double-left', 'Angle Double Left', '', '\uf100'],
  ['fa-angle-double-right', 'Angle Double Right', '', '\uf101'],
  ['fa-angle-double-up', 'Angle Double Up', '', '\uf102'],
  ['fa-angle-down', 'Angle Down', '', '\uf107'],
  ['fa-angle-left', 'Angle Left', '', '\uf104'],
  ['fa-angle-right', 'Angle Right', '', '\uf105'],
  ['fa-angle-up', 'Angle Up', '', '\uf106'],
  ['fa-apple', 'Apple', '', '\uf179'],
  ['fa-archive', 'Archive', '', '\uf187'],
  ['fa-area-chart', 'Area Chart', '', '\uf1fe'],
  ['fa-arrow-circle-down', 'Arrow Circle Down', '', '\uf0ab'],
  ['fa-arrow-circle-left', 'Arrow Circle Left', '', '\uf0a8'],
  ['fa-arrow-circle-o-down', 'Arrow Circle O Down', '', '\uf01a'],
  ['fa-arrow-circle-o-left', 'Arrow Circle O Left', '', '\uf190'],
  ['fa-arrow-circle-o-right', 'Arrow Circle O Right', '', '\uf18e'],
  ['fa-arrow-circle-o-up', 'Arrow Circle O Up', '', '\uf01b'],
  ['fa-arrow-circle-right', 'Arrow Circle Right', '', '\uf0a9'],
  ['fa-arrow-circle-up', 'Arrow Circle Up', '', '\uf0aa'],
  ['fa-arrow-down', 'Arrow Down', '', '\uf063'],
  ['fa-arrow-left', 'Arrow Left', '', '\uf060'],
  ['fa-arrow-right', 'Arrow Right', '', '\uf061'],
  ['fa-arrow-up', 'Arrow Up', '', '\uf062'],
  ['fa-arrows-alt', 'Arrows Alt', '', '\uf0b2'],
  ['fa-arrows-h', 'Arrows H', '', '\uf07e'],
  ['fa-arrows-v', 'Arrows V', '', '\uf07d'],
  ['fa-arrows', 'Arrows', '', '\uf047'],
  ['fa-asl-interpreting', 'Asl Interpreting', '', '\uf2a3'],
  [
    'fa-assistive-listening-systems',
    'Assistive Listening Systems',
    '',
    '\uf2a2',
  ],
  ['fa-asterisk', 'Asterisk', '', '\uf069'],
  ['fa-at', 'At', '', '\uf1fa'],
  ['fa-audio-description', 'Audio Description', '', '\uf29e'],
  ['fa-automobile', 'Automobile', '', '\uf1b9'],
  ['fa-backward', 'Backward', '', '\uf04a'],
  ['fa-balance-scale', 'Balance Scale', '', '\uf24e'],
  ['fa-ban', 'Ban', '', '\uf05e'],
  ['fa-bandcamp', 'Bandcamp', '', '\uf2d5'],
  ['fa-bank', 'Bank', '', '\uf19c'],
  ['fa-bar-chart-o', 'Bar Chart O', '', '\uf080'],
  ['fa-bar-chart', 'Bar Chart', '', '\uf080'],
  ['fa-barcode', 'Barcode', '', '\uf02a'],
  ['fa-bars', 'Bars', '', '\uf0c9'],
  ['fa-bath', 'Bath', '', '\uf2cd'],
  ['fa-bathtub', 'Bathtub', '', '\uf2cd'],
  ['fa-battery-0', 'Battery 0', '', '\uf244'],
  ['fa-battery-1', 'Battery 1', '', '\uf243'],
  ['fa-battery-2', 'Battery 2', '', '\uf242'],
  ['fa-battery-3', 'Battery 3', '', '\uf241'],
  ['fa-battery-4', 'Battery 4', '', '\uf240'],
  ['fa-battery-empty', 'Battery Empty', '', '\uf244'],
  ['fa-battery-full', 'Battery Full', '', '\uf240'],
  ['fa-battery-half', 'Battery Half', '', '\uf242'],
  ['fa-battery-quarter', 'Battery Quarter', '', '\uf243'],
  ['fa-battery-three-quarters', 'Battery Three Quarters', '', '\uf241'],
  ['fa-battery', 'Battery', '', '\uf240'],
  ['fa-bed', 'Bed', '', '\uf236'],
  ['fa-beer', 'Beer', '', '\uf0fc'],
  ['fa-behance-square', 'Behance Square', '', '\uf1b5'],
  ['fa-behance', 'Behance', '', '\uf1b4'],
  ['fa-bell-o', 'Bell O', '', '\uf0a2'],
  ['fa-bell-slash-o', 'Bell Slash O', '', '\uf1f7'],
  ['fa-bell-slash', 'Bell Slash', '', '\uf1f6'],
  ['fa-bell', 'Bell', '', '\uf0f3'],
  ['fa-bicycle', 'Bicycle', '', '\uf206'],
  ['fa-binoculars', 'Binoculars', '', '\uf1e5'],
  ['fa-birthday-cake', 'Birthday Cake', '', '\uf1fd'],
  ['fa-bitbucket-square', 'Bitbucket Square', '', '\uf172'],
  ['fa-bitbucket', 'Bitbucket', '', '\uf171'],
  ['fa-bitcoin', 'Bitcoin', '', '\uf15a'],
  ['fa-black-tie', 'Black Tie', '', '\uf27e'],
  ['fa-blind', 'Blind', '', '\uf29d'],
  ['fa-bluetooth-b', 'Bluetooth B', '', '\uf294'],
  ['fa-bluetooth', 'Bluetooth', '', '\uf293'],
  ['fa-bold', 'Bold', '', '\uf032'],
  ['fa-bolt', 'Bolt', '', '\uf0e7'],
  ['fa-bomb', 'Bomb', '', '\uf1e2'],
  ['fa-book', 'Book', '', '\uf02d'],
  ['fa-bookmark-o', 'Bookmark O', '', '\uf097'],
  ['fa-bookmark', 'Bookmark', '', '\uf02e'],
  ['fa-braille', 'Braille', '', '\uf2a1'],
  ['fa-briefcase', 'Briefcase', '', '\uf0b1'],
  ['fa-btc', 'Btc', '', '\uf15a'],
  ['fa-bug', 'Bug', '', '\uf188'],
  ['fa-building-o', 'Building O', '', '\uf0f7'],
  ['fa-building', 'Building', '', '\uf1ad'],
  ['fa-bullhorn', 'Bullhorn', '', '\uf0a1'],
  ['fa-bullseye', 'Bullseye', '', '\uf140'],
  ['fa-bus', 'Bus', '', '\uf207'],
  ['fa-buysellads', 'Buysellads', '', '\uf20d'],
  ['fa-cab', 'Cab', '', '\uf1ba'],
  ['fa-calculator', 'Calculator', '', '\uf1ec'],
  ['fa-calendar-check-o', 'Calendar Check O', '', '\uf274'],
  ['fa-calendar-minus-o', 'Calendar Minus O', '', '\uf272'],
  ['fa-calendar-o', 'Calendar O', '', '\uf133'],
  ['fa-calendar-plus-o', 'Calendar Plus O', '', '\uf271'],
  ['fa-calendar-times-o', 'Calendar Times O', '', '\uf273'],
  ['fa-calendar', 'Calendar', '', '\uf073'],
  ['fa-camera-retro', 'Camera Retro', '', '\uf083'],
  ['fa-camera', 'Camera', '', '\uf030'],
  ['fa-car', 'Car', '', '\uf1b9'],
  ['fa-caret-down', 'Caret Down', '', '\uf0d7'],
  ['fa-caret-left', 'Caret Left', '', '\uf0d9'],
  ['fa-caret-right', 'Caret Right', '', '\uf0da'],
  ['fa-caret-square-o-down', 'Caret Square O Down', '', '\uf150'],
  ['fa-caret-square-o-left', 'Caret Square O Left', '', '\uf191'],
  ['fa-caret-square-o-right', 'Caret Square O Right', '', '\uf152'],
  ['fa-caret-square-o-up', 'Caret Square O Up', '', '\uf151'],
  ['fa-caret-up', 'Caret Up', '', '\uf0d8'],
  ['fa-cart-arrow-down', 'Cart Arrow Down', '', '\uf218'],
  ['fa-cart-plus', 'Cart Plus', '', '\uf217'],
  ['fa-cc-amex', 'Cc Amex', '', '\uf1f3'],
  ['fa-cc-diners-club', 'Cc Diners Club', '', '\uf24c'],
  ['fa-cc-discover', 'Cc Discover', '', '\uf1f2'],
  ['fa-cc-jcb', 'Cc Jcb', '', '\uf24b'],
  ['fa-cc-mastercard', 'Cc Mastercard', '', '\uf1f1'],
  ['fa-cc-paypal', 'Cc Paypal', '', '\uf1f4'],
  ['fa-cc-stripe', 'Cc Stripe', '', '\uf1f5'],
  ['fa-cc-visa', 'Cc Visa', '', '\uf1f0'],
  ['fa-cc', 'Cc', '', '\uf20a'],
  ['fa-certificate', 'Certificate', '', '\uf0a3'],
  ['fa-chain-broken', 'Chain Broken', '', '\uf127'],
  ['fa-chain', 'Chain', '', '\uf0c1'],
  ['fa-check-circle-o', 'Check Circle O', '', '\uf05d'],
  ['fa-check-circle', 'Check Circle', '', '\uf058'],
  ['fa-check-square-o', 'Check Square O', '', '\uf046'],
  ['fa-check-square', 'Check Square', '', '\uf14a'],
  ['fa-check', 'Check', '', '\uf00c'],
  ['fa-chevron-circle-down', 'Chevron Circle Down', '', '\uf13a'],
  ['fa-chevron-circle-left', 'Chevron Circle Left', '', '\uf137'],
  ['fa-chevron-circle-right', 'Chevron Circle Right', '', '\uf138'],
  ['fa-chevron-circle-up', 'Chevron Circle Up', '', '\uf139'],
  ['fa-chevron-down', 'Chevron Down', '', '\uf078'],
  ['fa-chevron-left', 'Chevron Left', '', '\uf053'],
  ['fa-chevron-right', 'Chevron Right', '', '\uf054'],
  ['fa-chevron-up', 'Chevron Up', '', '\uf077'],
  ['fa-child', 'Child', '', '\uf1ae'],
  ['fa-chrome', 'Chrome', '', '\uf268'],
  ['fa-circle-o-notch', 'Circle O Notch', '', '\uf1ce'],
  ['fa-circle-o', 'Circle O', '', '\uf10c'],
  ['fa-circle-thin', 'Circle Thin', '', '\uf1db'],
  ['fa-circle', 'Circle', '', '\uf111'],
  ['fa-clipboard', 'Clipboard', '', '\uf0ea'],
  ['fa-clock-o', 'Clock O', '', '\uf017'],
  ['fa-clone', 'Clone', '', '\uf24d'],
  ['fa-close', 'Close', '', '\uf00d'],
  ['fa-cloud-download', 'Cloud Download', '', '\uf0ed'],
  ['fa-cloud-upload', 'Cloud Upload', '', '\uf0ee'],
  ['fa-cloud', 'Cloud', '', '\uf0c2'],
  ['fa-cny', 'Cny', '', '\uf157'],
  ['fa-code-fork', 'Code Fork', '', '\uf126'],
  ['fa-code', 'Code', '', '\uf121'],
  ['fa-codepen', 'Codepen', '', '\uf1cb'],
  ['fa-codiepie', 'Codiepie', '', '\uf284'],
  ['fa-coffee', 'Coffee', '', '\uf0f4'],
  ['fa-cog', 'Cog', '', '\uf013'],
  ['fa-cogs', 'Cogs', '', '\uf085'],
  ['fa-columns', 'Columns', '', '\uf0db'],
  ['fa-comment-o', 'Comment O', '', '\uf0e5'],
  ['fa-comment', 'Comment', '', '\uf075'],
  ['fa-commenting-o', 'Commenting O', '', '\uf27b'],
  ['fa-commenting', 'Commenting', '', '\uf27a'],
  ['fa-comments-o', 'Comments O', '', '\uf0e6'],
  ['fa-comments', 'Comments', '', '\uf086'],
  ['fa-compass', 'Compass', '', '\uf14e'],
  ['fa-compress', 'Compress', '', '\uf066'],
  ['fa-connectdevelop', 'Connectdevelop', '', '\uf20e'],
  ['fa-contao', 'Contao', '', '\uf26d'],
  ['fa-copy', 'Copy', '', '\uf0c5'],
  ['fa-copyright', 'Copyright', '', '\uf1f9'],
  ['fa-creative-commons', 'Creative Commons', '', '\uf25e'],
  ['fa-credit-card-alt', 'Credit Card Alt', '', '\uf283'],
  ['fa-credit-card', 'Credit Card', '', '\uf09d'],
  ['fa-crop', 'Crop', '', '\uf125'],
  ['fa-crosshairs', 'Crosshairs', '', '\uf05b'],
  ['fa-css3', 'Css3', '', '\uf13c'],
  ['fa-cube', 'Cube', '', '\uf1b2'],
  ['fa-cubes', 'Cubes', '', '\uf1b3'],
  ['fa-cut', 'Cut', '', '\uf0c4'],
  ['fa-cutlery', 'Cutlery', '', '\uf0f5'],
  ['fa-dashboard', 'Dashboard', '', '\uf0e4'],
  ['fa-dashcube', 'Dashcube', '', '\uf210'],
  ['fa-database', 'Database', '', '\uf1c0'],
  ['fa-deaf', 'Deaf', '', '\uf2a4'],
  ['fa-deafness', 'Deafness', '', '\uf2a4'],
  ['fa-dedent', 'Dedent', '', '\uf03b'],
  ['fa-delicious', 'Delicious', '', '\uf1a5'],
  ['fa-desktop', 'Desktop', '', '\uf108'],
  ['fa-deviantart', 'Deviantart', '', '\uf1bd'],
  ['fa-diamond', 'Diamond', '', '\uf219'],
  ['fa-digg', 'Digg', '', '\uf1a6'],
  ['fa-dollar', 'Dollar', '', '\uf155'],
  ['fa-dot-circle-o', 'Dot Circle O', '', '\uf192'],
  ['fa-download', 'Download', '', '\uf019'],
  ['fa-dribbble', 'Dribbble', '', '\uf17d'],
  ['fa-drivers-license-o', 'Drivers License O', '', '\uf2c3'],
  ['fa-drivers-license', 'Drivers License', '', '\uf2c2'],
  ['fa-dropbox', 'Dropbox', '', '\uf16b'],
  ['fa-drupal', 'Drupal', '', '\uf1a9'],
  ['fa-edge', 'Edge', '', '\uf282'],
  ['fa-edit', 'Edit', '', '\uf044'],
  ['fa-eercast', 'Eercast', '', '\uf2da'],
  ['fa-eject', 'Eject', '', '\uf052'],
  ['fa-ellipsis-h', 'Ellipsis H', '', '\uf141'],
  ['fa-ellipsis-v', 'Ellipsis V', '', '\uf142'],
  ['fa-empire', 'Empire', '', '\uf1d1'],
  ['fa-envelope-o', 'Envelope O', '', '\uf003'],
  ['fa-envelope-open-o', 'Envelope Open O', '', '\uf2b7'],
  ['fa-envelope-open', 'Envelope Open', '', '\uf2b6'],
  ['fa-envelope-square', 'Envelope Square', '', '\uf199'],
  ['fa-envelope', 'Envelope', '', '\uf0e0'],
  ['fa-envira', 'Envira', '', '\uf299'],
  ['fa-eraser', 'Eraser', '', '\uf12d'],
  ['fa-etsy', 'Etsy', '', '\uf2d7'],
  ['fa-eur', 'Eur', '', '\uf153'],
  ['fa-euro', 'Euro', '', '\uf153'],
  ['fa-exchange', 'Exchange', '', '\uf0ec'],
  ['fa-exclamation-circle', 'Exclamation Circle', '', '\uf06a'],
  ['fa-exclamation-triangle', 'Exclamation Triangle', '', '\uf071'],
  ['fa-exclamation', 'Exclamation', '', '\uf12a'],
  ['fa-expand', 'Expand', '', '\uf065'],
  ['fa-expeditedssl', 'Expeditedssl', '', '\uf23e'],
  ['fa-external-link-square', 'External Link Square', '', '\uf14c'],
  ['fa-external-link', 'External Link', '', '\uf08e'],
  ['fa-eye-slash', 'Eye Slash', '', '\uf070'],
  ['fa-eye', 'Eye', '', '\uf06e'],
  ['fa-eyedropper', 'Eyedropper', '', '\uf1fb'],
  ['fa-fa', 'Fa', '', '\uf2b4'],
  ['fa-facebook-f', 'Facebook F', '', '\uf09a'],
  ['fa-facebook-official', 'Facebook Official', '', '\uf230'],
  ['fa-facebook-square', 'Facebook Square', '', '\uf082'],
  ['fa-facebook', 'Facebook', '', '\uf09a'],
  ['fa-fast-backward', 'Fast Backward', '', '\uf049'],
  ['fa-fast-forward', 'Fast Forward', '', '\uf050'],
  ['fa-fax', 'Fax', '', '\uf1ac'],
  ['fa-feed', 'Feed', '', '\uf09e'],
  ['fa-female', 'Female', '', '\uf182'],
  ['fa-fighter-jet', 'Fighter Jet', '', '\uf0fb'],
  ['fa-file-archive-o', 'File Archive O', '', '\uf1c6'],
  ['fa-file-audio-o', 'File Audio O', '', '\uf1c7'],
  ['fa-file-code-o', 'File Code O', '', '\uf1c9'],
  ['fa-file-excel-o', 'File Excel O', '', '\uf1c3'],
  ['fa-file-image-o', 'File Image O', '', '\uf1c5'],
  ['fa-file-movie-o', 'File Movie O', '', '\uf1c8'],
  ['fa-file-o', 'File O', '', '\uf016'],
  ['fa-file-pdf-o', 'File Pdf O', '', '\uf1c1'],
  ['fa-file-photo-o', 'File Photo O', '', '\uf1c5'],
  ['fa-file-picture-o', 'File Picture O', '', '\uf1c5'],
  ['fa-file-powerpoint-o', 'File Powerpoint O', '', '\uf1c4'],
  ['fa-file-sound-o', 'File Sound O', '', '\uf1c7'],
  ['fa-file-text-o', 'File Text O', '', '\uf0f6'],
  ['fa-file-text', 'File Text', '', '\uf15c'],
  ['fa-file-video-o', 'File Video O', '', '\uf1c8'],
  ['fa-file-word-o', 'File Word O', '', '\uf1c2'],
  ['fa-file-zip-o', 'File Zip O', '', '\uf1c6'],
  ['fa-file', 'File', '', '\uf15b'],
  ['fa-files-o', 'Files O', '', '\uf0c5'],
  ['fa-film', 'Film', '', '\uf008'],
  ['fa-filter', 'Filter', '', '\uf0b0'],
  ['fa-fire-extinguisher', 'Fire Extinguisher', '', '\uf134'],
  ['fa-fire', 'Fire', '', '\uf06d'],
  ['fa-firefox', 'Firefox', '', '\uf269'],
  ['fa-first-order', 'First Order', '', '\uf2b0'],
  ['fa-flag-checkered', 'Flag Checkered', '', '\uf11e'],
  ['fa-flag-o', 'Flag O', '', '\uf11d'],
  ['fa-flag', 'Flag', '', '\uf024'],
  ['fa-flash', 'Flash', '', '\uf0e7'],
  ['fa-flask', 'Flask', '', '\uf0c3'],
  ['fa-flickr', 'Flickr', '', '\uf16e'],
  ['fa-floppy-o', 'Floppy O', '', '\uf0c7'],
  ['fa-folder-o', 'Folder O', '', '\uf114'],
  ['fa-folder-open-o', 'Folder Open O', '', '\uf115'],
  ['fa-folder-open', 'Folder Open', '', '\uf07c'],
  ['fa-folder', 'Folder', '', '\uf07b'],
  ['fa-font-awesome', 'Font Awesome', '', '\uf2b4'],
  ['fa-font', 'Font', '', '\uf031'],
  ['fa-fonticons', 'Fonticons', '', '\uf280'],
  ['fa-fort-awesome', 'Fort Awesome', '', '\uf286'],
  ['fa-forumbee', 'Forumbee', '', '\uf211'],
  ['fa-forward', 'Forward', '', '\uf04e'],
  ['fa-foursquare', 'Foursquare', '', '\uf180'],
  ['fa-free-code-camp', 'Free Code Camp', '', '\uf2c5'],
  ['fa-frown-o', 'Frown O', '', '\uf119'],
  ['fa-futbol-o', 'Futbol O', '', '\uf1e3'],
  ['fa-gamepad', 'Gamepad', '', '\uf11b'],
  ['fa-gavel', 'Gavel', '', '\uf0e3'],
  ['fa-gbp', 'Gbp', '', '\uf154'],
  ['fa-ge', 'Ge', '', '\uf1d1'],
  ['fa-gear', 'Gear', '', '\uf013'],
  ['fa-gears', 'Gears', '', '\uf085'],
  ['fa-genderless', 'Genderless', '', '\uf22d'],
  ['fa-get-pocket', 'Get Pocket', '', '\uf265'],
  ['fa-gg-circle', 'Gg Circle', '', '\uf261'],
  ['fa-gg', 'Gg', '', '\uf260'],
  ['fa-gift', 'Gift', '', '\uf06b'],
  ['fa-git-square', 'Git Square', '', '\uf1d2'],
  ['fa-git', 'Git', '', '\uf1d3'],
  ['fa-github-alt', 'Github Alt', '', '\uf113'],
  ['fa-github-square', 'Github Square', '', '\uf092'],
  ['fa-github', 'Github', '', '\uf09b'],
  ['fa-gitlab', 'Gitlab', '', '\uf296'],
  ['fa-gittip', 'Gittip', '', '\uf184'],
  ['fa-glass', 'Glass', '', '\uf000'],
  ['fa-glide-g', 'Glide G', '', '\uf2a6'],
  ['fa-glide', 'Glide', '', '\uf2a5'],
  ['fa-globe', 'Globe', '', '\uf0ac'],
  ['fa-google-plus-circle', 'Google Plus Circle', '', '\uf2b3'],
  ['fa-google-plus-official', 'Google Plus Official', '', '\uf2b3'],
  ['fa-google-plus-square', 'Google Plus Square', '', '\uf0d4'],
  ['fa-google-plus', 'Google Plus', '', '\uf0d5'],
  ['fa-google-wallet', 'Google Wallet', '', '\uf1ee'],
  ['fa-google', 'Google', '', '\uf1a0'],
  ['fa-graduation-cap', 'Graduation Cap', '', '\uf19d'],
  ['fa-gratipay', 'Gratipay', '', '\uf184'],
  ['fa-grav', 'Grav', '', '\uf2d6'],
  ['fa-group', 'Group', '', '\uf0c0'],
  ['fa-h-square', 'H Square', '', '\uf0fd'],
  ['fa-hacker-news', 'Hacker News', '', '\uf1d4'],
  ['fa-hand-grab-o', 'Hand Grab O', '', '\uf255'],
  ['fa-hand-lizard-o', 'Hand Lizard O', '', '\uf258'],
  ['fa-hand-o-down', 'Hand O Down', '', '\uf0a7'],
  ['fa-hand-o-left', 'Hand O Left', '', '\uf0a5'],
  ['fa-hand-o-right', 'Hand O Right', '', '\uf0a4'],
  ['fa-hand-o-up', 'Hand O Up', '', '\uf0a6'],
  ['fa-hand-paper-o', 'Hand Paper O', '', '\uf256'],
  ['fa-hand-peace-o', 'Hand Peace O', '', '\uf25b'],
  ['fa-hand-pointer-o', 'Hand Pointer O', '', '\uf25a'],
  ['fa-hand-rock-o', 'Hand Rock O', '', '\uf255'],
  ['fa-hand-scissors-o', 'Hand Scissors O', '', '\uf257'],
  ['fa-hand-spock-o', 'Hand Spock O', '', '\uf259'],
  ['fa-hand-stop-o', 'Hand Stop O', '', '\uf256'],
  ['fa-handshake-o', 'Handshake O', '', '\uf2b5'],
  ['fa-hard-of-hearing', 'Hard Of Hearing', '', '\uf2a4'],
  ['fa-hashtag', 'Hashtag', '', '\uf292'],
  ['fa-hdd-o', 'Hdd O', '', '\uf0a0'],
  ['fa-header', 'Header', '', '\uf1dc'],
  ['fa-headphones', 'Headphones', '', '\uf025'],
  ['fa-heart-o', 'Heart O', '', '\uf08a'],
  ['fa-heart', 'Heart', '', '\uf004'],
  ['fa-heartbeat', 'Heartbeat', '', '\uf21e'],
  ['fa-history', 'History', '', '\uf1da'],
  ['fa-home', 'Home', '', '\uf015'],
  ['fa-hospital-o', 'Hospital O', '', '\uf0f8'],
  ['fa-hotel', 'Hotel', '', '\uf236'],
  ['fa-hourglass-1', 'Hourglass 1', '', '\uf251'],
  ['fa-hourglass-2', 'Hourglass 2', '', '\uf252'],
  ['fa-hourglass-3', 'Hourglass 3', '', '\uf253'],
  ['fa-hourglass-end', 'Hourglass End', '', '\uf253'],
  ['fa-hourglass-half', 'Hourglass Half', '', '\uf252'],
  ['fa-hourglass-o', 'Hourglass O', '', '\uf250'],
  ['fa-hourglass-start', 'Hourglass Start', '', '\uf251'],
  ['fa-hourglass', 'Hourglass', '', '\uf254'],
  ['fa-houzz', 'Houzz', '', '\uf27c'],
  ['fa-html5', 'Html5', '', '\uf13b'],
  ['fa-i-cursor', 'I Cursor', '', '\uf246'],
  ['fa-id-badge', 'Id Badge', '', '\uf2c1'],
  ['fa-id-card-o', 'Id Card O', '', '\uf2c3'],
  ['fa-id-card', 'Id Card', '', '\uf2c2'],
  ['fa-ils', 'Ils', '', '\uf20b'],
  ['fa-image', 'Image', '', '\uf03e'],
  ['fa-imdb', 'Imdb', '', '\uf2d8'],
  ['fa-inbox', 'Inbox', '', '\uf01c'],
  ['fa-indent', 'Indent', '', '\uf03c'],
  ['fa-industry', 'Industry', '', '\uf275'],
  ['fa-info-circle', 'Info Circle', '', '\uf05a'],
  ['fa-info', 'Info', '', '\uf129'],
  ['fa-inr', 'Inr', '', '\uf156'],
  ['fa-instagram', 'Instagram', '', '\uf16d'],
  ['fa-institution', 'Institution', '', '\uf19c'],
  ['fa-internet-explorer', 'Internet Explorer', '', '\uf26b'],
  ['fa-intersex', 'Intersex', '', '\uf224'],
  ['fa-ioxhost', 'Ioxhost', '', '\uf208'],
  ['fa-italic', 'Italic', '', '\uf033'],
  ['fa-joomla', 'Joomla', '', '\uf1aa'],
  ['fa-jpy', 'Jpy', '', '\uf157'],
  ['fa-jsfiddle', 'Jsfiddle', '', '\uf1cc'],
  ['fa-key', 'Key', '', '\uf084'],
  ['fa-keyboard-o', 'Keyboard O', '', '\uf11c'],
  ['fa-krw', 'Krw', '', '\uf159'],
  ['fa-language', 'Language', '', '\uf1ab'],
  ['fa-laptop', 'Laptop', '', '\uf109'],
  ['fa-lastfm-square', 'Lastfm Square', '', '\uf203'],
  ['fa-lastfm', 'Lastfm', '', '\uf202'],
  ['fa-leaf', 'Leaf', '', '\uf06c'],
  ['fa-leanpub', 'Leanpub', '', '\uf212'],
  ['fa-legal', 'Legal', '', '\uf0e3'],
  ['fa-lemon-o', 'Lemon O', '', '\uf094'],
  ['fa-level-down', 'Level Down', '', '\uf149'],
  ['fa-level-up', 'Level Up', '', '\uf148'],
  ['fa-life-bouy', 'Life Bouy', '', '\uf1cd'],
  ['fa-life-buoy', 'Life Buoy', '', '\uf1cd'],
  ['fa-life-ring', 'Life Ring', '', '\uf1cd'],
  ['fa-life-saver', 'Life Saver', '', '\uf1cd'],
  ['fa-lightbulb-o', 'Lightbulb O', '', '\uf0eb'],
  ['fa-line-chart', 'Line Chart', '', '\uf201'],
  ['fa-link', 'Link', '', '\uf0c1'],
  ['fa-linkedin-square', 'Linkedin Square', '', '\uf08c'],
  ['fa-linkedin', 'Linkedin', '', '\uf0e1'],
  ['fa-linode', 'Linode', '', '\uf2b8'],
  ['fa-linux', 'Linux', '', '\uf17c'],
  ['fa-list-alt', 'List Alt', '', '\uf022'],
  ['fa-list-ol', 'List Ol', '', '\uf0cb'],
  ['fa-list-ul', 'List Ul', '', '\uf0ca'],
  ['fa-list', 'List', '', '\uf03a'],
  ['fa-location-arrow', 'Location Arrow', '', '\uf124'],
  ['fa-lock', 'Lock', '', '\uf023'],
  ['fa-long-arrow-down', 'Long Arrow Down', '', '\uf175'],
  ['fa-long-arrow-left', 'Long Arrow Left', '', '\uf177'],
  ['fa-long-arrow-right', 'Long Arrow Right', '', '\uf178'],
  ['fa-long-arrow-up', 'Long Arrow Up', '', '\uf176'],
  ['fa-low-vision', 'Low Vision', '', '\uf2a8'],
  ['fa-magic', 'Magic', '', '\uf0d0'],
  ['fa-magnet', 'Magnet', '', '\uf076'],
  ['fa-mail-forward', 'Mail Forward', '', '\uf064'],
  ['fa-mail-reply-all', 'Mail Reply All', '', '\uf122'],
  ['fa-mail-reply', 'Mail Reply', '', '\uf112'],
  ['fa-male', 'Male', '', '\uf183'],
  ['fa-map-marker', 'Map Marker', '', '\uf041'],
  ['fa-map-o', 'Map O', '', '\uf278'],
  ['fa-map-pin', 'Map Pin', '', '\uf276'],
  ['fa-map-signs', 'Map Signs', '', '\uf277'],
  ['fa-map', 'Map', '', '\uf279'],
  ['fa-mars-double', 'Mars Double', '', '\uf227'],
  ['fa-mars-stroke-h', 'Mars Stroke H', '', '\uf22b'],
  ['fa-mars-stroke-v', 'Mars Stroke V', '', '\uf22a'],
  ['fa-mars-stroke', 'Mars Stroke', '', '\uf229'],
  ['fa-mars', 'Mars', '', '\uf222'],
  ['fa-maxcdn', 'Maxcdn', '', '\uf136'],
  ['fa-meanpath', 'Meanpath', '', '\uf20c'],
  ['fa-medium', 'Medium', '', '\uf23a'],
  ['fa-medkit', 'Medkit', '', '\uf0fa'],
  ['fa-meetup', 'Meetup', '', '\uf2e0'],
  ['fa-meh-o', 'Meh O', '', '\uf11a'],
  ['fa-mercury', 'Mercury', '', '\uf223'],
  ['fa-microchip', 'Microchip', '', '\uf2db'],
  ['fa-microphone-slash', 'Microphone Slash', '', '\uf131'],
  ['fa-microphone', 'Microphone', '', '\uf130'],
  ['fa-minus-circle', 'Minus Circle', '', '\uf056'],
  ['fa-minus-square-o', 'Minus Square O', '', '\uf147'],
  ['fa-minus-square', 'Minus Square', '', '\uf146'],
  ['fa-minus', 'Minus', '', '\uf068'],
  ['fa-mixcloud', 'Mixcloud', '', '\uf289'],
  ['fa-mobile-phone', 'Mobile Phone', '', '\uf10b'],
  ['fa-mobile', 'Mobile', '', '\uf10b'],
  ['fa-modx', 'Modx', '', '\uf285'],
  ['fa-money', 'Money', '', '\uf0d6'],
  ['fa-moon-o', 'Moon O', '', '\uf186'],
  ['fa-mortar-board', 'Mortar Board', '', '\uf19d'],
  ['fa-motorcycle', 'Motorcycle', '', '\uf21c'],
  ['fa-mouse-pointer', 'Mouse Pointer', '', '\uf245'],
  ['fa-music', 'Music', '', '\uf001'],
  ['fa-navicon', 'Navicon', '', '\uf0c9'],
  ['fa-neuter', 'Neuter', '', '\uf22c'],
  ['fa-newspaper-o', 'Newspaper O', '', '\uf1ea'],
  ['fa-object-group', 'Object Group', '', '\uf247'],
  ['fa-object-ungroup', 'Object Ungroup', '', '\uf248'],
  ['fa-odnoklassniki-square', 'Odnoklassniki Square', '', '\uf264'],
  ['fa-odnoklassniki', 'Odnoklassniki', '', '\uf263'],
  ['fa-opencart', 'Opencart', '', '\uf23d'],
  ['fa-openid', 'Openid', '', '\uf19b'],
  ['fa-opera', 'Opera', '', '\uf26a'],
  ['fa-optin-monster', 'Optin Monster', '', '\uf23c'],
  ['fa-outdent', 'Outdent', '', '\uf03b'],
  ['fa-pagelines', 'Pagelines', '', '\uf18c'],
  ['fa-paint-brush', 'Paint Brush', '', '\uf1fc'],
  ['fa-paper-plane-o', 'Paper Plane O', '', '\uf1d9'],
  ['fa-paper-plane', 'Paper Plane', '', '\uf1d8'],
  ['fa-paperclip', 'Paperclip', '', '\uf0c6'],
  ['fa-paragraph', 'Paragraph', '', '\uf1dd'],
  ['fa-paste', 'Paste', '', '\uf0ea'],
  ['fa-pause-circle-o', 'Pause Circle O', '', '\uf28c'],
  ['fa-pause-circle', 'Pause Circle', '', '\uf28b'],
  ['fa-pause', 'Pause', '', '\uf04c'],
  ['fa-paw', 'Paw', '', '\uf1b0'],
  ['fa-paypal', 'Paypal', '', '\uf1ed'],
  ['fa-pencil-square-o', 'Pencil Square O', '', '\uf044'],
  ['fa-pencil-square', 'Pencil Square', '', '\uf14b'],
  ['fa-pencil', 'Pencil', '', '\uf040'],
  ['fa-percent', 'Percent', '', '\uf295'],
  ['fa-phone-square', 'Phone Square', '', '\uf098'],
  ['fa-phone', 'Phone', '', '\uf095'],
  ['fa-photo', 'Photo', '', '\uf03e'],
  ['fa-picture-o', 'Picture O', '', '\uf03e'],
  ['fa-pie-chart', 'Pie Chart', '', '\uf200'],
  ['fa-pied-piper-alt', 'Pied Piper Alt', '', '\uf1a8'],
  ['fa-pied-piper-pp', 'Pied Piper Pp', '', '\uf1a7'],
  ['fa-pied-piper', 'Pied Piper', '', '\uf2ae'],
  ['fa-pinterest-p', 'Pinterest P', '', '\uf231'],
  ['fa-pinterest-square', 'Pinterest Square', '', '\uf0d3'],
  ['fa-pinterest', 'Pinterest', '', '\uf0d2'],
  ['fa-plane', 'Plane', '', '\uf072'],
  ['fa-play-circle-o', 'Play Circle O', '', '\uf01d'],
  ['fa-play-circle', 'Play Circle', '', '\uf144'],
  ['fa-play', 'Play', '', '\uf04b'],
  ['fa-plug', 'Plug', '', '\uf1e6'],
  ['fa-plus-circle', 'Plus Circle', '', '\uf055'],
  ['fa-plus-square-o', 'Plus Square O', '', '\uf196'],
  ['fa-plus-square', 'Plus Square', '', '\uf0fe'],
  ['fa-plus', 'Plus', '', '\uf067'],
  ['fa-podcast', 'Podcast', '', '\uf2ce'],
  ['fa-power-off', 'Power Off', '', '\uf011'],
  ['fa-print', 'Print', '', '\uf02f'],
  ['fa-product-hunt', 'Product Hunt', '', '\uf288'],
  ['fa-puzzle-piece', 'Puzzle Piece', '', '\uf12e'],
  ['fa-qq', 'Qq', '', '\uf1d6'],
  ['fa-qrcode', 'Qrcode', '', '\uf029'],
  ['fa-question-circle-o', 'Question Circle O', '', '\uf29c'],
  ['fa-question-circle', 'Question Circle', '', '\uf059'],
  ['fa-question', 'Question', '', '\uf128'],
  ['fa-quora', 'Quora', '', '\uf2c4'],
  ['fa-quote-left', 'Quote Left', '', '\uf10d'],
  ['fa-quote-right', 'Quote Right', '', '\uf10e'],
  ['fa-ra', 'Ra', '', '\uf1d0'],
  ['fa-random', 'Random', '', '\uf074'],
  ['fa-ravelry', 'Ravelry', '', '\uf2d9'],
  ['fa-rebel', 'Rebel', '', '\uf1d0'],
  ['fa-recycle', 'Recycle', '', '\uf1b8'],
  ['fa-reddit-alien', 'Reddit Alien', '', '\uf281'],
  ['fa-reddit-square', 'Reddit Square', '', '\uf1a2'],
  ['fa-reddit', 'Reddit', '', '\uf1a1'],
  ['fa-refresh', 'Refresh', '', '\uf021'],
  ['fa-registered', 'Registered', '', '\uf25d'],
  ['fa-remove', 'Remove', '', '\uf00d'],
  ['fa-renren', 'Renren', '', '\uf18b'],
  ['fa-reorder', 'Reorder', '', '\uf0c9'],
  ['fa-repeat', 'Repeat', '', '\uf01e'],
  ['fa-reply-all', 'Reply All', '', '\uf122'],
  ['fa-reply', 'Reply', '', '\uf112'],
  ['fa-resistance', 'Resistance', '', '\uf1d0'],
  ['fa-retweet', 'Retweet', '', '\uf079'],
  ['fa-rmb', 'Rmb', '', '\uf157'],
  ['fa-road', 'Road', '', '\uf018'],
  ['fa-rocket', 'Rocket', '', '\uf135'],
  ['fa-rotate-left', 'Rotate Left', '', '\uf0e2'],
  ['fa-rotate-right', 'Rotate Right', '', '\uf01e'],
  ['fa-rouble', 'Rouble', '', '\uf158'],
  ['fa-rss-square', 'Rss Square', '', '\uf143'],
  ['fa-rss', 'Rss', '', '\uf09e'],
  ['fa-rub', 'Rub', '', '\uf158'],
  ['fa-ruble', 'Ruble', '', '\uf158'],
  ['fa-rupee', 'Rupee', '', '\uf156'],
  ['fa-s15', 'S15', '', '\uf2cd'],
  ['fa-safari', 'Safari', '', '\uf267'],
  ['fa-save', 'Save', '', '\uf0c7'],
  ['fa-scissors', 'Scissors', '', '\uf0c4'],
  ['fa-scribd', 'Scribd', '', '\uf28a'],
  ['fa-search-minus', 'Search Minus', '', '\uf010'],
  ['fa-search-plus', 'Search Plus', '', '\uf00e'],
  ['fa-search', 'Search', '', '\uf002'],
  ['fa-sellsy', 'Sellsy', '', '\uf213'],
  ['fa-send-o', 'Send O', '', '\uf1d9'],
  ['fa-send', 'Send', '', '\uf1d8'],
  ['fa-server', 'Server', '', '\uf233'],
  ['fa-share-alt-square', 'Share Alt Square', '', '\uf1e1'],
  ['fa-share-alt', 'Share Alt', '', '\uf1e0'],
  ['fa-share-square-o', 'Share Square O', '', '\uf045'],
  ['fa-share-square', 'Share Square', '', '\uf14d'],
  ['fa-share', 'Share', '', '\uf064'],
  ['fa-shekel', 'Shekel', '', '\uf20b'],
  ['fa-sheqel', 'Sheqel', '', '\uf20b'],
  ['fa-shield', 'Shield', '', '\uf132'],
  ['fa-ship', 'Ship', '', '\uf21a'],
  ['fa-shirtsinbulk', 'Shirtsinbulk', '', '\uf214'],
  ['fa-shopping-bag', 'Shopping Bag', '', '\uf290'],
  ['fa-shopping-basket', 'Shopping Basket', '', '\uf291'],
  ['fa-shopping-cart', 'Shopping Cart', '', '\uf07a'],
  ['fa-shower', 'Shower', '', '\uf2cc'],
  ['fa-sign-in', 'Sign In', '', '\uf090'],
  ['fa-sign-language', 'Sign Language', '', '\uf2a7'],
  ['fa-sign-out', 'Sign Out', '', '\uf08b'],
  ['fa-signal', 'Signal', '', '\uf012'],
  ['fa-signing', 'Signing', '', '\uf2a7'],
  ['fa-simplybuilt', 'Simplybuilt', '', '\uf215'],
  ['fa-sitemap', 'Sitemap', '', '\uf0e8'],
  ['fa-skyatlas', 'Skyatlas', '', '\uf216'],
  ['fa-skype', 'Skype', '', '\uf17e'],
  ['fa-slack', 'Slack', '', '\uf198'],
  ['fa-sliders', 'Sliders', '', '\uf1de'],
  ['fa-slideshare', 'Slideshare', '', '\uf1e7'],
  ['fa-smile-o', 'Smile O', '', '\uf118'],
  ['fa-snapchat-ghost', 'Snapchat Ghost', '', '\uf2ac'],
  ['fa-snapchat-square', 'Snapchat Square', '', '\uf2ad'],
  ['fa-snapchat', 'Snapchat', '', '\uf2ab'],
  ['fa-snowflake-o', 'Snowflake O', '', '\uf2dc'],
  ['fa-soccer-ball-o', 'Soccer Ball O', '', '\uf1e3'],
  ['fa-sort-alpha-asc', 'Sort Alpha Asc', '', '\uf15d'],
  ['fa-sort-alpha-desc', 'Sort Alpha Desc', '', '\uf15e'],
  ['fa-sort-amount-asc', 'Sort Amount Asc', '', '\uf160'],
  ['fa-sort-amount-desc', 'Sort Amount Desc', '', '\uf161'],
  ['fa-sort-asc', 'Sort Asc', '', '\uf0de'],
  ['fa-sort-desc', 'Sort Desc', '', '\uf0dd'],
  ['fa-sort-down', 'Sort Down', '', '\uf0dd'],
  ['fa-sort-numeric-asc', 'Sort Numeric Asc', '', '\uf162'],
  ['fa-sort-numeric-desc', 'Sort Numeric Desc', '', '\uf163'],
  ['fa-sort-up', 'Sort Up', '', '\uf0de'],
  ['fa-sort', 'Sort', '', '\uf0dc'],
  ['fa-soundcloud', 'Soundcloud', '', '\uf1be'],
  ['fa-space-shuttle', 'Space Shuttle', '', '\uf197'],
  ['fa-spinner', 'Spinner', '', '\uf110'],
  ['fa-spoon', 'Spoon', '', '\uf1b1'],
  ['fa-spotify', 'Spotify', '', '\uf1bc'],
  ['fa-square-o', 'Square O', '', '\uf096'],
  ['fa-square', 'Square', '', '\uf0c8'],
  ['fa-stack-exchange', 'Stack Exchange', '', '\uf18d'],
  ['fa-stack-overflow', 'Stack Overflow', '', '\uf16c'],
  ['fa-star-half-empty', 'Star Half Empty', '', '\uf123'],
  ['fa-star-half-full', 'Star Half Full', '', '\uf123'],
  ['fa-star-half-o', 'Star Half O', '', '\uf123'],
  ['fa-star-half', 'Star Half', '', '\uf089'],
  ['fa-star-o', 'Star O', '', '\uf006'],
  ['fa-star', 'Star', '', '\uf005'],
  ['fa-steam-square', 'Steam Square', '', '\uf1b7'],
  ['fa-steam', 'Steam', '', '\uf1b6'],
  ['fa-step-backward', 'Step Backward', '', '\uf048'],
  ['fa-step-forward', 'Step Forward', '', '\uf051'],
  ['fa-stethoscope', 'Stethoscope', '', '\uf0f1'],
  ['fa-sticky-note-o', 'Sticky Note O', '', '\uf24a'],
  ['fa-sticky-note', 'Sticky Note', '', '\uf249'],
  ['fa-stop-circle-o', 'Stop Circle O', '', '\uf28e'],
  ['fa-stop-circle', 'Stop Circle', '', '\uf28d'],
  ['fa-stop', 'Stop', '', '\uf04d'],
  ['fa-street-view', 'Street View', '', '\uf21d'],
  ['fa-strikethrough', 'Strikethrough', '', '\uf0cc'],
  ['fa-stumbleupon-circle', 'Stumbleupon Circle', '', '\uf1a3'],
  ['fa-stumbleupon', 'Stumbleupon', '', '\uf1a4'],
  ['fa-subscript', 'Subscript', '', '\uf12c'],
  ['fa-subway', 'Subway', '', '\uf239'],
  ['fa-suitcase', 'Suitcase', '', '\uf0f2'],
  ['fa-sun-o', 'Sun O', '', '\uf185'],
  ['fa-superpowers', 'Superpowers', '', '\uf2dd'],
  ['fa-superscript', 'Superscript', '', '\uf12b'],
  ['fa-support', 'Support', '', '\uf1cd'],
  ['fa-table', 'Table', '', '\uf0ce'],
  ['fa-tablet', 'Tablet', '', '\uf10a'],
  ['fa-tachometer', 'Tachometer', '', '\uf0e4'],
  ['fa-tag', 'Tag', '', '\uf02b'],
  ['fa-tags', 'Tags', '', '\uf02c'],
  ['fa-tasks', 'Tasks', '', '\uf0ae'],
  ['fa-taxi', 'Taxi', '', '\uf1ba'],
  ['fa-telegram', 'Telegram', '', '\uf2c6'],
  ['fa-television', 'Television', '', '\uf26c'],
  ['fa-tencent-weibo', 'Tencent Weibo', '', '\uf1d5'],
  ['fa-terminal', 'Terminal', '', '\uf120'],
  ['fa-text-height', 'Text Height', '', '\uf034'],
  ['fa-text-width', 'Text Width', '', '\uf035'],
  ['fa-th-large', 'Th Large', '', '\uf009'],
  ['fa-th-list', 'Th List', '', '\uf00b'],
  ['fa-th', 'Th', '', '\uf00a'],
  ['fa-themeisle', 'Themeisle', '', '\uf2b2'],
  ['fa-thermometer-0', 'Thermometer 0', '', '\uf2cb'],
  ['fa-thermometer-1', 'Thermometer 1', '', '\uf2ca'],
  ['fa-thermometer-2', 'Thermometer 2', '', '\uf2c9'],
  ['fa-thermometer-3', 'Thermometer 3', '', '\uf2c8'],
  ['fa-thermometer-4', 'Thermometer 4', '', '\uf2c7'],
  ['fa-thermometer-empty', 'Thermometer Empty', '', '\uf2cb'],
  ['fa-thermometer-full', 'Thermometer Full', '', '\uf2c7'],
  ['fa-thermometer-half', 'Thermometer Half', '', '\uf2c9'],
  ['fa-thermometer-quarter', 'Thermometer Quarter', '', '\uf2ca'],
  [
    'fa-thermometer-three-quarters',
    'Thermometer Three Quarters',
    '',
    '\uf2c8',
  ],
  ['fa-thermometer', 'Thermometer', '', '\uf2c7'],
  ['fa-thumb-tack', 'Thumb Tack', '', '\uf08d'],
  ['fa-thumbs-down', 'Thumbs Down', '', '\uf165'],
  ['fa-thumbs-o-down', 'Thumbs O Down', '', '\uf088'],
  ['fa-thumbs-o-up', 'Thumbs O Up', '', '\uf087'],
  ['fa-thumbs-up', 'Thumbs Up', '', '\uf164'],
  ['fa-ticket', 'Ticket', '', '\uf145'],
  ['fa-times-circle-o', 'Times Circle O', '', '\uf05c'],
  ['fa-times-circle', 'Times Circle', '', '\uf057'],
  ['fa-times-rectangle-o', 'Times Rectangle O', '', '\uf2d4'],
  ['fa-times-rectangle', 'Times Rectangle', '', '\uf2d3'],
  ['fa-times', 'Times', '', '\uf00d'],
  ['fa-tint', 'Tint', '', '\uf043'],
  ['fa-toggle-down', 'Toggle Down', '', '\uf150'],
  ['fa-toggle-left', 'Toggle Left', '', '\uf191'],
  ['fa-toggle-off', 'Toggle Off', '', '\uf204'],
  ['fa-toggle-on', 'Toggle On', '', '\uf205'],
  ['fa-toggle-right', 'Toggle Right', '', '\uf152'],
  ['fa-toggle-up', 'Toggle Up', '', '\uf151'],
  ['fa-trademark', 'Trademark', '', '\uf25c'],
  ['fa-train', 'Train', '', '\uf238'],
  ['fa-transgender-alt', 'Transgender Alt', '', '\uf225'],
  ['fa-transgender', 'Transgender', '', '\uf224'],
  ['fa-trash-o', 'Trash O', '', '\uf014'],
  ['fa-trash', 'Trash', '', '\uf1f8'],
  ['fa-tree', 'Tree', '', '\uf1bb'],
  ['fa-trello', 'Trello', '', '\uf181'],
  ['fa-tripadvisor', 'Tripadvisor', '', '\uf262'],
  ['fa-trophy', 'Trophy', '', '\uf091'],
  ['fa-truck', 'Truck', '', '\uf0d1'],
  ['fa-try', 'Try', '', '\uf195'],
  ['fa-tty', 'Tty', '', '\uf1e4'],
  ['fa-tumblr-square', 'Tumblr Square', '', '\uf174'],
  ['fa-tumblr', 'Tumblr', '', '\uf173'],
  ['fa-turkish-lira', 'Turkish Lira', '', '\uf195'],
  ['fa-tv', 'Tv', '', '\uf26c'],
  ['fa-twitch', 'Twitch', '', '\uf1e8'],
  ['fa-twitter-square', 'Twitter Square', '', '\uf081'],
  ['fa-twitter', 'Twitter', '', '\uf099'],
  ['fa-umbrella', 'Umbrella', '', '\uf0e9'],
  ['fa-underline', 'Underline', '', '\uf0cd'],
  ['fa-undo', 'Undo', '', '\uf0e2'],
  ['fa-universal-access', 'Universal Access', '', '\uf29a'],
  ['fa-university', 'University', '', '\uf19c'],
  ['fa-unlink', 'Unlink', '', '\uf127'],
  ['fa-unlock-alt', 'Unlock Alt', '', '\uf13e'],
  ['fa-unlock', 'Unlock', '', '\uf09c'],
  ['fa-unsorted', 'Unsorted', '', '\uf0dc'],
  ['fa-upload', 'Upload', '', '\uf093'],
  ['fa-usb', 'Usb', '', '\uf287'],
  ['fa-usd', 'Usd', '', '\uf155'],
  ['fa-user-circle-o', 'User Circle O', '', '\uf2be'],
  ['fa-user-circle', 'User Circle', '', '\uf2bd'],
  ['fa-user-md', 'User Md', '', '\uf0f0'],
  ['fa-user-o', 'User O', '', '\uf2c0'],
  ['fa-user-plus', 'User Plus', '', '\uf234'],
  ['fa-user-secret', 'User Secret', '', '\uf21b'],
  ['fa-user-times', 'User Times', '', '\uf235'],
  ['fa-user', 'User', '', '\uf007'],
  ['fa-users', 'Users', '', '\uf0c0'],
  ['fa-vcard-o', 'Vcard O', '', '\uf2bc'],
  ['fa-vcard', 'Vcard', '', '\uf2bb'],
  ['fa-venus-double', 'Venus Double', '', '\uf226'],
  ['fa-venus-mars', 'Venus Mars', '', '\uf228'],
  ['fa-venus', 'Venus', '', '\uf221'],
  ['fa-viacoin', 'Viacoin', '', '\uf237'],
  ['fa-viadeo-square', 'Viadeo Square', '', '\uf2aa'],
  ['fa-viadeo', 'Viadeo', '', '\uf2a9'],
  ['fa-video-camera', 'Video Camera', '', '\uf03d'],
  ['fa-vimeo-square', 'Vimeo Square', '', '\uf194'],
  ['fa-vimeo', 'Vimeo', '', '\uf27d'],
  ['fa-vine', 'Vine', '', '\uf1ca'],
  ['fa-vk', 'Vk', '', '\uf189'],
  ['fa-volume-control-phone', 'Volume Control Phone', '', '\uf2a0'],
  ['fa-volume-down', 'Volume Down', '', '\uf027'],
  ['fa-volume-off', 'Volume Off', '', '\uf026'],
  ['fa-volume-up', 'Volume Up', '', '\uf028'],
  ['fa-warning', 'Warning', '', '\uf071'],
  ['fa-wechat', 'Wechat', '', '\uf1d7'],
  ['fa-weibo', 'Weibo', '', '\uf18a'],
  ['fa-weixin', 'Weixin', '', '\uf1d7'],
  ['fa-whatsapp', 'Whatsapp', '', '\uf232'],
  ['fa-wheelchair-alt', 'Wheelchair Alt', '', '\uf29b'],
  ['fa-wheelchair', 'Wheelchair', '', '\uf193'],
  ['fa-wifi', 'Wifi', '', '\uf1eb'],
  ['fa-wikipedia-w', 'Wikipedia W', '', '\uf266'],
  ['fa-window-close-o', 'Window Close O', '', '\uf2d4'],
  ['fa-window-close', 'Window Close', '', '\uf2d3'],
  ['fa-window-maximize', 'Window Maximize', '', '\uf2d0'],
  ['fa-window-minimize', 'Window Minimize', '', '\uf2d1'],
  ['fa-window-restore', 'Window Restore', '', '\uf2d2'],
  ['fa-windows', 'Windows', '', '\uf17a'],
  ['fa-won', 'Won', '', '\uf159'],
  ['fa-wordpress', 'Wordpress', '', '\uf19a'],
  ['fa-wpbeginner', 'Wpbeginner', '', '\uf297'],
  ['fa-wpexplorer', 'Wpexplorer', '', '\uf2de'],
  ['fa-wpforms', 'Wpforms', '', '\uf298'],
  ['fa-wrench', 'Wrench', '', '\uf0ad'],
  ['fa-xing-square', 'Xing Square', '', '\uf169'],
  ['fa-xing', 'Xing', '', '\uf168'],
  ['fa-y-combinator-square', 'Y Combinator Square', '', '\uf1d4'],
  ['fa-y-combinator', 'Y Combinator', '', '\uf23b'],
  ['fa-yahoo', 'Yahoo', '', '\uf19e'],
  ['fa-yc-square', 'Yc Square', '', '\uf1d4'],
  ['fa-yc', 'Yc', '', '\uf23b'],
  ['fa-yelp', 'Yelp', '', '\uf1e9'],
  ['fa-yen', 'Yen', '', '\uf157'],
  ['fa-yoast', 'Yoast', '', '\uf2b1'],
  ['fa-youtube-play', 'Youtube Play', '', '\uf16a'],
  ['fa-youtube-square', 'Youtube Square', '', '\uf166'],
  ['fa-youtube', 'Youtube', '', '\uf167'],
];
